services:
    manga_bot:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - type: volume
            source: bot_data
            target: /app/data

          - type: bind
            source: #указать папку в которой будут хранится логи
            target: /app/logs

        deploy:
          restart_policy:
            condition: on-failure
            delay: 5s

volumes:
    bot_data:
